Merge the Fedora patch to add labeled networking. 	Patch xinetd-2.3.14-label.patch r1.4. Merge the Fedora patch to fix getpeercon() for labeled networking 	in MLS environments. 	Patch xinetd-2.3.14-contextconf.patch r1.1

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -852,6 +852,7 @@ Optional Packages:
 
   --with-inet6    Compile in ipv6 support. (obsolete)
   --with-libwrap=PATH   Compile in libwrap (tcp_wrappers) support.
+  --with-labeled-networking=PATH   Compile in labeled networking support.
 
 Some influential environment variables:
   CC          C compiler command
@@ -9213,6 +9214,116 @@ echo "$as_me: error: Could not find the $withval library.  You must first instal
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
+		;;
+	esac
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
+fi;
+
+echo "$as_me:$LINENO: checking whether to use labeled-networking" >&5
+echo $ECHO_N "checking whether to use labeled-networking... $ECHO_C" >&6
+
+# Check whether --with-labeled-networking or --without-labeled-networking was given.
+if test "${with_labeled_networking+set}" = set; then
+  withval="$with_labeled_networking"
+   case "$withval" in
+	no)
+		echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+		;;
+	yes)
+		echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+		echo "$as_me:$LINENO: checking for setexeccon in -lselinux" >&5
+echo $ECHO_N "checking for setexeccon in -lselinux... $ECHO_C" >&6
+if test "${ac_cv_lib_selinux_setexeccon+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lselinux  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char setexeccon ();
+int
+main ()
+{
+setexeccon ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_selinux_setexeccon=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_selinux_setexeccon=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_selinux_setexeccon" >&5
+echo "${ECHO_T}$ac_cv_lib_selinux_setexeccon" >&6
+if test $ac_cv_lib_selinux_setexeccon = yes; then
+
+			cat >>confdefs.h <<\_ACEOF
+#define LABELED_NET 1
+_ACEOF
+
+			LABELLIBS="-lselinux"
+fi
+
+		LIBS="$LABELLIBS $LIBS"
+		;;
+	*)
+		echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+		cat >>confdefs.h <<\_ACEOF
+#define LABELED_NET 1
+_ACEOF
+
+		if test -d "$withval"; then
+			LABELLIBS="-L$withval -lselinux"
+		else
+			LABELLIBS="$withval"
+		fi
+		LIBS="$LABELLIBS $LIBS"
 		;;
 	esac
 else
